from string import ascii_letters, digits

APPROVED_SYMBOLS = ascii_letters + digits
ORIGINAL_LINK_LENGTH = 1024
RANDOM_GEN_TRYS = 3
SHORT_LINK_LENGTH = 16
SHORT_LINK_RANDOM_LENGTH = 6
SHORT_LINK_REXEXP = f'[{APPROVED_SYMBOLS}]+'
SHORT_LINK_FUNCTION_NAME = 'link_redirect_view'
